<?php

namespace AppBundle\Repository;

/**
 * LicenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenceRepository extends \Doctrine\ORM\EntityRepository
{
}
